source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'

  gem 'therubyracer'
  gem 'less-rails', '~> 2.2.6'

  # Bootstrap (http://twitter.github.com/bootstrap) in its original Less form.
  # gem 'bootstrap-sass' is also good, but for working closely with Bootstrap, I prefer to use Less.
  gem "twitter-bootstrap-rails", "~> 2.2.0"

  gem 'eco'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
