// Generated by CoffeeScript 1.3.1
(function() {
  var root;

  root = this;

  root.Score = Backbone.Model.extend({
    defaults: {
      points: 0
    }
  });

  root.Scores = Backbone.Collection.extend({
    model: Score
  });

}).call(this);
